### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-manage-user#2]
Don't we want to specify a password for the account [here](https://github.com/cisagov/ansible-manage-user/blob/develop/create/playbook.yml#L6-L9)?

You can generate the `crypt`ed password via `mkpasswd --method=sha-512` and put it in SSM.  The `crypt`ed value is even safe to commit to git, although I don't think there is any need for that here.  (There is no known way to retrieve the password from the `crypt`ed value.)

**Comment by dav3r** [comment]
I believe this issue is OBE. By design, the user we create can only be accessed via public key authentication.
